#!/bin/sh

set -e

FILE="$1"

# Extract images
pdfimages -j "$FILE" "$FILE"

# Extract text
pdftotext "$FILE" > "$FILE".txt

# OCR
for file in "$FILE"-[0-9][0-9][0-9].jpg
  do
  tesseract "$file" "$file"
  echo "$file.txt" >> "$FILE.txt"
done
