#!/bin/sh

set -e
. ./papers.sh
set -e

if [ "$1" != nodownload ]
  then
  # Save the listing page.
  python2 listing.py
fi

tsv=$(mktemp)
while true
  do
  # Save unprocessed pdf files, and stop when finished
  tsvtext="$(python2 get_unprocessed.py tsv)"
  echo "${tsvtext}" | sed 1d > $tsv

  permit=$(cat $tsv|cut -f1)
  url="http://www.mvn.usace.army.mil/ops/regulatory/$(cat $tsv|cut -f2)"
  papertype=$(cat $tsv|cut -f3)
  
  dir="pdfs/$permit"

  echo '------------------------------------------------------------'
  echo Working on the "${permit} ${papertype}"
  echo '------------------------------------------------------------'

  # Has the file been downloaded? Download if not.
  file=$(paper \
    --permit "${permit}" \
    --url "${url}" \
    --papertype "${papertype}") || already_downloaded=true

  # If the file has been downloaded, then it clearly hasn't been parsed fully
  # because get_unprocessed.py returns it; run the translator.
  ./translate "${file}" || ocr_error=true

  # Read the text and save it.
  cat "${file}".txt | python2 read.py "${permit}" "${papertype}"

  # If the OCR raised an error, remember that.
  if $ocr_error
    then
    echo OCR error>&2
    # Record OCR error
    if [ "${papertype}" = public_notice ]
      then
      paperType=publicNotice
    elif [ "${papertype}" = drawings ]
    then
      paperType=drawings
    fi
    mongo wetlands --eval "db.permit.insert({_id:\"${permit}\",${paperType}:{ocrError:true}})"
  fi

  echo \ 
  echo '------------------------------------------------------------'
  echo \ 
  echo \ 
  echo \ 
done
